### ISSUE TITLE
[Parser] Update parser to upload info about all the Iowa facilities

### ISSUE THREAD

**Issue by gabrielsaruhashi** [Ameelio/connect-api-nest#154]
**Describe the bug**
Jason scheduled a recurring email to be sent out with all information of the incarcerated population in Iowa.
It has the same fields as before + an extra "facility name" column

**To-Do**
- [ ] Create facility records for the entire state (9 in total)
- [ ] Update the parser to locate the right facility for the incarcerated person
- [ ] Parser should automatically create a 'root' Group node that represents the facility level (this will be useful in case Kiosks are shared across the entire facility)

**Additional context**
@lspdrz I'll forward you a CSV so you can take a look
